package utils;

public final class CONSTS {
	public static final int LANGUAGE_CHINESE=1;
	public static final int LANGUAGE_ENGLISH=0;
	public static final String[] MENU_STRING_USER= {"User","用户"};
	public static final String[] MENU_STRING_LOGIN= {"Login","登录"};
	public static final String[] MENU_STRING_NOTEPAD= {"Notepad","生词本"};
	public static final String[] MENU_STRING_EXIT= {"Exit","退出"};
	public static final String[] MENU_STRING_OPTION= {"Option","选项"};
	public static final String[] MENU_STRING_SETTINGS= {"Settings","设置"};
	public static final String[] MENU_STRING_ABOUT= {"About","关于"};
	public static final String[] MENU_STRING_AUTHOR= {"Author","作者"};
	public static final String[] MENU_STRING_VERSION= {"Version","版本"};
	public static final String[] MAINFRAME_BTN_SEARCH_TEXT= {"Search","查询"};
	public static final String[] MAINFRAME_BTN_ADDTONP_TEXT= {"Add to notepad","添加到生词本"};
	public static final String[] MAINFRAME_TITLE= {"SDUT ENGLISH LEARNING SYSTEM","SDUT大学英语学习系统"};
	public static final String[] LOGIN_TITLE= {"Login","登录"};
	public static final String[] LOGIN_TIP_USERNAME= {"User","用户名"};
	public static final String[] LOGIN_TIP_PASSWORD= {"Password","密码"};
	public static final String[] LOGIN_BUTTON_LOGIN= {"Login","登录"};
	public static final String[] LOGIN_BUTTON_REGESTOR= {"Sing up","注册"};
	public static final String[] LOGIN_STRING_LOGIN_FAILED= {"Login failed!","登录失败"};
	public static final String WORD_LIST_SPLIT="\\#";
	public static final String LOGIN_USER_ALREADY_EXISTS[]= {"User already exists!","用户已存在！"};
	public static final String LOGIN_USER_REG_SUCCESS[]= {"Create User Success!","用户创建成功！"};
	public static final String NOTEPAD_BUTTON_REMOVE[]= {"Remove from list","从生词表移除"};
	public static final String NOTEPAD_BUTTON_REMEBER[]= {"Let's remenber those","开始背单词"};
	public static final String NOTEPAD_TITLE[]= {"Notepad","生词本"};
	public static final String MAIN_FRAME_LOGIN_FIRST[]= {"Please login first!","请先登录"};
	public static final String REMEMBER_TITLE[]= {"Remember","背单词"};
	public static final String REMEMBER_BUTTON_VIEWMEANING[]= {"View meaning","查看释义"};
	public static final String REMEMBER_BUTTON_REMEMBERED[]= {"I'v remembered","我记住了"};
	public static final String REMEMBER_TIP_YOUNOWORDS[]= {"You don't have any word in notepad!","你的生词本中没有单词！"};
	public static final String REMEMBER_TIP_ALL[]= {"You don't have any word needing to remember!","你已经记完所有单词！"};
	public static final char CONFIG_STRING_SPLIT='=';
	public static final String STRING_LANGUAGE_CHINESE="chinese";
	public static final String STRING_LANGUAGE_ENGLISH="english";
	public static final String SETTINGS_RADIO_CHINESE[]= {"中文","Chinese"};
	public static final String SETTINGS_RADIO_ENGLISG[]= {"英语","English"};
	public static final String SETTINGS_TITLE[]= {"Settings","设置"};
	public static final String SETTINGS_SET_SUCCESS[]= {"Set success,restart program to apply!","设置成功，重启生效！"};
	public static final String AUTHOR="SDUT wslGroup";
	public static final String VERSION="1.0"; 
}
